import Player from "./bananaPlayer"

type submittedCard = {
    SubmitterSocketID: string
    SubmitterScreenName: string
    CardText: string
    WinningCard: boolean
}

type LoginInfo = {
    ScreenName: string
    SentFrom: string
    Password: string
    Mascot: string
}

type ChatMessage = {
    ID: number
    Type: "GameMessage" | "PlayerMessage"
    SenderScreenName: string
    SenderChatHandle: string
    Text: string
}


export default class BananaGame {

    private gameState: "Not Started" | "Round: Submitting Cards" | "Round: Tzar Selection" | "Round: Results"
    private password: string
    private playerCards: string[]
    private promptCards: string[]
    private currentPromptCard: string
    private submittedCards: submittedCard[]
    private cardTzar: number
    private players: Player[]
    private loggedOutPlayers: Player[]
    private chatMessages: ChatMessage[]


    constructor()
    {
        this.gameState = "Not Started"
        this.password = "gutterfolk"
        this.players = []
        this.loggedOutPlayers = []
        this.cardTzar = -1
        this.playerCards = this.shuffleStringArray(this.playerCardsUnshuffled)
        this.promptCards = this.shuffleStringArray(this.promptCardsUnshuffled)
        this.chatMessages = []
    }

    public get GameState() : string { return this.gameState }

    public get Players() : Player[] { return this.players }

    public get CurrentPrompt() : string { return this.currentPromptCard }

    public get SubmittedCards() : submittedCard[] {return this.submittedCards}

    public get RoundWinnerScreenName() : string 
    {
        for (let card of this.submittedCards)
            if (card.WinningCard)
                return card.SubmitterScreenName
        return "Nobody"
    }

    public get ChatMessages() : ChatMessage[] {return this.chatMessages}



    public addNewPlayer(loginInfo: LoginInfo) : string {
        // Check the info sent from the client
        for (let player of this.players) {
            if (player.ScreenName === loginInfo.ScreenName)
                return "There is someone already logged in with this name." }
        if (loginInfo.Password != this.password)
            return "Password is invalid."
        if (loginInfo.Mascot === null)
            return "Please select a mascot."

        if (this.players.length >= 6)
            return "I'm sorry, there are currently the max number of players logged in!"

        // Either create a new player or update the information of someone who was logged out
        let newPlayer: Player = this.findAndPullLoggedOffPlayer(loginInfo.ScreenName)
        if (newPlayer === null)
        {
            let initialPlayerCards: string[] = this.drawFullPlayerCardHand()
            newPlayer = new Player(loginInfo.SentFrom, loginInfo.ScreenName, loginInfo.Mascot, initialPlayerCards)
            this.players.push(newPlayer)
        }
        else
        {
            newPlayer.updatePlayerInfo(loginInfo.SentFrom, loginInfo.Mascot)
            while (newPlayer.PlayerCards.length < 6) {
                newPlayer.addNewCard(this.playerCards.pop())
            }
            this.players.push(newPlayer)
        }

        if (newPlayer.CardTzar === true)
            newPlayer.setCardTzarStatus(false)

        return ""
    }

    public getPlayerBySocketID(socketID: string) : Player {
        for (let player of this.players) {
            if (player.SocketID === socketID)
                return player
        }
        return null
    }

    public getPlayerByScreenName(screenName: string) : Player {
        for (let player of this.players) {
            if (player.ScreenName === screenName)
                return player
        }
        return null
    }

    public removePlayerBySocketID(socketID: string) : boolean {
        let playerForRemoval : Player = this.getPlayerBySocketID(socketID)
        let newPlayersList: Player[] = []
        
        for (let player of this.players) {
            if (player.SocketID === socketID)
                this.loggedOutPlayers.push(player)
            else  
                newPlayersList.push(player)
        }

        this.players = newPlayersList

        if (this.gameState === "Not Started" || this.gameState === "Round: Results")
            return false
        else //A round is currently in play
            return true
    }


    public findAndPullLoggedOffPlayer(screenName: string): Player {
        let newPlayersList: Player[] = []
        let PlayerToReturn: Player = null
        
        for (let player of this.loggedOutPlayers) {
            if (player.ScreenName === screenName)
                PlayerToReturn = player
            else  
                newPlayersList.push(player)
        }

        this.loggedOutPlayers = newPlayersList
        return PlayerToReturn  
    }

    public drawNextPromptCard(): boolean {
        if (this.promptCards.length != 0)
            this.currentPromptCard = this.promptCards.pop()
        else
            return false

        return true
    }

    public drawFullPlayerCardHand(): string[] {
        let sixCards: string[] = []
        for (var i=0; i<6; i++)
            sixCards.push(this.playerCards.pop())

        return sixCards
    }

    public drawOnePlayerCard(): string {
        let nextCard: string
        if (this.playerCards.length != 0)
            nextCard = this.playerCards.pop()
        else
            nextCard = ""

        return nextCard
    }

    public assignNextCardTzar() {
        this.cardTzar += 1
        if (this.cardTzar >= this.players.length)
            this.cardTzar = 0

        for (var i=0; i<this.players.length; i++) {
            if (i === this.cardTzar)
                this.players[i].setCardTzarStatus(true)
            else
                this.players[i].setCardTzarStatus(false)
        }
    }

    public changeGameStatus(newGameState:"Not Started" | "Round: Submitting Cards" | "Round: Tzar Selection" | "Round: Results") {
        this.gameState = newGameState

        if (newGameState === "Round: Submitting Cards")
        {
            this.submittedCards = []
            this.assignNextCardTzar()
            this.drawNextPromptCard()
    
            for (let player of this.players) {
                if (player.PlayerCards.length != 6)
                    player.addNewCard(this.drawOnePlayerCard())  
            }
        }
    }


    public playerCardSubmission(playerSocketID: string, cardID: number): string
    {
        //console.log(this.gameState)
        if (this.gameState != "Round: Submitting Cards")
            return "Submission not permitted at this time."
        let submittingPlayer: Player = this.getPlayerBySocketID(playerSocketID)
        if (submittingPlayer === null)
            return "Could not find this player on the server."
        if (submittingPlayer.CardTzar === true)
            return "Card Tzar cannot submit in this round."
        if (submittingPlayer.PlayerCards.length === 5)
            return "Card already played for this round."
        if (cardID < 0 || cardID > 6)
            return "Card could not be found on the server."
        
        let newSubmittedCard = <submittedCard>{SubmitterSocketID: playerSocketID, 
            SubmitterScreenName: submittingPlayer.ScreenName, 
            CardText: submittingPlayer.PlayerCards[cardID], WinningCard: false}
        this.submittedCards.push(newSubmittedCard)
        submittingPlayer.removeCardByIndex(cardID)

        return ""
    }


    public submitCardTzarSelection (tzarSocketID: string, cardID: number): string 
    {
        if (this.gameState != "Round: Tzar Selection")
            return "Card Tzar selection not permitted at this time."
        let submittingPlayer: Player = this.getPlayerBySocketID(tzarSocketID)
        if (submittingPlayer === null)
            return "Could not find this player on the server."
        if (submittingPlayer.CardTzar === false)
            return "Player not currently selected as Card Tzar"
        if (this.submittedCards.length < 2)
            return "Not enough cards have been submitted for this round."
        if (cardID < 0 || cardID > this.submittedCards.length - 1)
            return "Card selected could not be found."
        
        let winningCard: submittedCard = this.submittedCards[cardID]
        let winningPlayer: Player = this.getPlayerBySocketID(winningCard.SubmitterSocketID)
        if (winningPlayer === null)
            return "Player who won this round could not be found on the server."
        
        winningCard.WinningCard = true        
        winningPlayer.addPoint()
        this.changeGameStatus("Round: Results")
        return ""
    }


    public DiscardPlayerCard (playerSocketID: string, cardID: number) : string
    {
        let requestingPlayer: Player = this.getPlayerBySocketID(playerSocketID)
        if (requestingPlayer === null)
            return "Could not find this player on the server."
        if (requestingPlayer.DiscardsRemaining === 0)
            return "Maximum number of discards reached."
        if (cardID < 0 || cardID > requestingPlayer.PlayerCards.length)
            return "Card could not be found on the server."

        requestingPlayer.PlayerCards.splice(cardID, 1) //Removes the cardID'th item in the array
        requestingPlayer.addNewCard(this.drawOnePlayerCard())
        requestingPlayer.DeincrementDiscardAllowance()
        return ""
    }


    private shuffleStringArray (inputArray: string[]) : string[]
    {
        let inputArrayCopy: string[] = inputArray
        let returnArray: string[] = []

        while (inputArrayCopy.length > 0) {
            let randIndex = Math.floor(Math.random() * inputArrayCopy.length)
            if (randIndex === inputArrayCopy.length) randIndex -= 1

            returnArray.push(inputArrayCopy[randIndex])
            inputArrayCopy.splice(randIndex, 1)
        }

        return returnArray
    }


    public AddNewChatMessage(messageType: "GameMessage" | "PlayerMessage", sender: Player, chatMessage: string)
    {
        let newChatMessage: ChatMessage
        let newID: number = this.chatMessages.length + 1

        if (messageType === "PlayerMessage")
        {
            if (sender === null)
                newChatMessage = <ChatMessage>{ID: newID, Type: "PlayerMessage", 
                    SenderScreenName: "Unknown", SenderChatHandle: "?", Text: chatMessage}
            else
                newChatMessage = <ChatMessage>{ID: newID, Type: "PlayerMessage", 
                    SenderScreenName: sender.ScreenName, SenderChatHandle: sender.ChatHandle, 
                    Text: chatMessage}
        }
        else
            newChatMessage = <ChatMessage>{ID: newID, Type: "GameMessage", SenderScreenName: "Game",
             SenderChatHandle: "🍌", Text: chatMessage}

        this.chatMessages.push(newChatMessage)
    }


  




    private playerCardsUnshuffled = [
    "Discovering that what I really want in life is to count penguins",
    "Desperately hurling insults at Trump as he absorbs them into his rapidly expanding body",
    "Mitt Romney's eight sons Kip, Sam, Trot, Fergis, Toolshed, Grisham, Hawkeye, and Thorp",
    "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying",
    "A beautiful, ever-expanding circle of inclusivity that will never include Republicans",
    "Calling mom because it's just really hard and I miss her and I don't know anyone here",
    "A cat video so cute that YouTube breaks",
    "Judging hamsters by the color of their fur and not by the content of their character",
    "Allowing nacho cheese to curdle in your beard while you watch Disney movies",
    "Laying in the bathtub and whispering 'tonight, I will have sex with Tom Cruise'",
    "Buying virtual clothes for a Sim family instead of real clothes for a real family",
    "Ironically buying a trucker hat and then ironically being a trucker for 38 years",
    "A bunch of idiots playing a card game instead of interacting like normal humans",
    "Free ice cream forever, or making out with Chris Hemsworth for five minutes",
    "How wonderful it is when my master throws the ball and I go and get it for him",
    "Getting bitten by a radioactive spider and then battling leukemia for 30 years",
    "Actually voting for Donald Trump to be President of the actual United States",
    "Going on an epic adventure and learning a valuable lesson about friendship",
    "Covering myself with Parmesan cheese and chili flakes because I am pizza",
    "A dolphin that learns to talk and becomes the Dean of Harvard Law School",
    "Winning the approval of your boss that you never got from your mother",
    "Seeing what happens when you lock people in a room with hungry seagulls",
    "An immediately regrettable $9 hot dog from the Boston Convention Center",
    "10 football players with blindfolds barreling towards you at full speed",
    "My abusive boyfriend who really isn't so bad once you get to know him",
    "The graceful path of an autumn leaf as it falls to its earthen cradle",
    "Dropping dead in a Chili's bathroom and not being found for 72 hours",
    "Throwing your hands in the air and waving them despite caring deeply",
    "Roaming through a wasteland of windblown trash and deserted highways",
    "Drinking ten 5-Hour Energy shots to get fifty continuous hours of energy",
    "Discovering some stupid microscopic life instead of anything cool",
    "Stuffing a HotPocket into a Sega Genesis and pressing the power button",
    "Holding up the line at Walgreens by trying to use an expired coupon",
    "Pretending to be one of the guys but actually being the spider god",
    "Giving money and personal information to strangers on the Internet",
    "An alternate universe in which boxes store things inside of people",
    "Accidentally conjuring a legless horse that loves reality TV",
    "Gender-neutral toys that make children feel no emotions whatsoever",
    "Throwing a baby dolphin back into the ocean with a perfect spiral",
    "A father and son fighting each other over the last deviled egg",
    "Pizza in the morning, pizza in the evening, pizza at supper time",
    "Absolutely crushing the middle class with a regressive tax code",
    "A nightmare starring Sigourney Weaver and the Cookie Monster",
    "Handcuffing a wizard to a radiator and making him watch Friends",
    "Stuffing a child's face with Fun Dip until he starts having fun",
    "Putting an entire peanut butter and jelly sandwich into the VCR",
    "Your mom pretending she doesn't have a favorite child",
    "A gender identity that can only be conveyed through slam poetry",
    "People with cake in their mouths talking about how good cake is",
    "A box of biscuits, a box of mixed biscuits, and a biscuit mixer",
    "A dwarf who won't leave you alone until you agree to rub his tummy",
    "Being an attractive elf trapped in an unattractive human's body",
    "A man in a suit with perfect hair who tells you beautiful lies",
    "An X-Man whose power is that he makes artisanal soaps",
    "Smashing all the pottery in a Pottery Barn in search of horses",
    "A grumpy old Harrison Ford who'd rather be doing anything else",
    "Running naked through a mall, asking for high fives",
    "A sofa that says 'I have style, but I like to be comfortable.'",
    "Making up for 10 years of bad parenting with a PlayStation",
    "Spending the year's insulin budget on Air Jordans",
    "Swishing the wine around and sniffing it like a big fancy man",
    "Getting really worried about global warming for a few seconds",
    "Letting Bernie Sanders rest his world-weary head on your lap",
    "Chugging a gallon of milk and then discovering you're lactose intolerant",
    "Dinosaurs who wear armor and you ride them and they kick ass",
    "A magical kingdom with dragons and elves and no Donald Trump",
    "Never watching, discussing, or thinking about My Little Pony",
    "Becoming so rich that you shed your body and turn into vapor",
    "Buying and returning clothes just to have someone to talk to",
    "A complete inability to understand anyone else's perspective",
    "Men discussing their feelings in an emotionally healthy way",
    "Something that looks like a box but turns out to be a crate",
    "Being emotionally devastated by Gordon Ramsay",
    "A disappointing season of Game of Thrones that's just about taxes",
    "Throwing grapes at a man until he loses touch with reality",
    "A pansexual octopus who roams the cosmos in search of love",
    "Wondering if it's possible to get some of that salsa to go",
    "Summoning Aquaman from the sea in a time of great need",
    "A bus that will explode if it goes under 50 miles per hour",
    "The Hawaiian goddess Kapo and her flying moose sidekick",
    "A cloud of ash that darkens the Earth for a thousand years",
    "That thing politicians do with their thumbs when they talk",
    "A respectful discussion of race and gender on the Internet",
    "Actual mutants with medical conditions and no superpowers",
    "The complex geopolitical quagmire that is the Middle East",
    "Sitting in a jar of vinegar all night because I am pickle",
    "Finding out that democracy might not be such a great idea",
    "An octopus writing 7 emails and smoking a cigarette",
    "A man in yoga pants with a ponytail and feather earrings",
    "Bathing in moonsblood and dancing around the ancient oak",
    "Every ounce of charisma left in Mick Jagger's tired body",
    "Reaching an age where barbecue chips are better than sex",
    "Rising sea levels consistent with scientific predictions",
    "A slow, stupid car that drives around Mars for no reason",
    "A little boy who won't shut up about dinosaurs",
    "My complicated backstory that you will soon learn about",
    "Forgetting to convert pound-seconds into newton-seconds",
    "Whipping lower-class white men into a xenophobic frenzy",
    "Having big dreams but no realistic way to achieve them",
    "Listening to her problems without trying to solve them",
    "Bill Clinton, naked on a bearskin rug with a saxophone",
    "The clown that followed me home from the grocery store",
    "Several intertwining love stories featuring Hugh Grant",
    "Mixing M&M's and Skittles like some kind of psychopath",
    "Getting tickled by the Blue Man Group",
    "A thrilling chase over the rooftops of Rio de Janeiro",
    "Angels interfering in an otherwise fair baseball game",
    "Giving ISIS whatever they want so they leave us alone",
    "How cool it is that I love Jesus and he loves me back",
    "Dining with cardboard cutouts of the cast of Friends",
    "Eating a crouton out of my husband's bellybutton",
    "Going inside at some point because of the mosquitoes",
    "A woman who is so cool that she rides on a motorcycle",
    "A man with the head of a goat and the body of a goat",
    "Working so hard to have muscles and then having them",
    "Big, smart money boys tap-tapping on their keyboards",
    "Breastfeeding in public like a radiant earth goddess",
    "Dreaming of going to space, but being hopelessly fat",
    "Rubbing Boris Johnson's belly until he falls asleep",
    "Being a busy adult with many important things to do",
    "Swearing praise upon the Sultan's hideous daughters",
    "Liking big butts and not being able to lie about it",
    "Stupid Christmas cards with no money in them",
    "A box that is conscious and wishes it weren't a box",
    "A girl who is so interesting that she has blue hair",
    "The Dial-A-Slice Apple Divider from Williams-Sonoma",
    "Sucking down thousands of pounds of krill every day",
    "A madman who lives in a telephone booth and kidnaps women",
    "Going too far with science and bad things happening",
    "That thing on the Internet everyone's talking about",
    "David Bowie flying in on a tiger made of lightning",
    "The basic suffering that pervades all of existence",
    "The feeling of going to McDonald's as a 6-year-old",
    "A weird guy who says weird stuff and weirds me out",
    "Falling in actual love with a video game character",
    "A snowman that contains the soul of my deceased father",
    "Going vegetarian and feeling so great all the time",
    "Getting butt implants from a Mexican cyborg doctor",
    "The penny whistle solo from 'My Heart Will Go On'",
    "Emerging from the sea and rampaging through Tokyo",
    "The prunes I've been saving for you in my armpits",
    "Not contributing to society in any meaningful way",
    "The total collapse of the global financial system",
    "Setting my feet on fire and cartwheeling to Ohio",
    "Quacking like a duck in lieu of a cogent argument",
    "A strong horse and enough rations for thirty days",
    "Donald Trump holding his nose while he eats vegetables",
    "Screwing up 'Silent Night' in front of 300 parents",
    "Courageously going ahead with that racist comment",
    "What to do with all of this chocolate on my ears",
    "A German-style board game where you invade Poland",
    "Ruth Bader Ginsburg beating you in a slam dunk competition",
    "Anything that comes out of Prince Philip's mouth",
    "Subduing a grizzly bear and making her your wife",
    "Spilling your apple juice all over the floor like a fool",
    "Destroying your neighbor's horde of lawn flamingos",
    "Getting trapped in a conversation about Ayn Rand",
    "Licking the elbows of the beat boxer from the a cappella group",
    "Drinking Beyonce's lemonade and becoming immortal",
    "Buying the right toothbrush cup for my lifestyle",
    "Not vaccinating my children because I am stupid",
    "How bad my daughter messed up her dance recital",
    "Sneezing, farting, and stubbing your toe at the same time",
    "An unhinged Ferris wheel rolling toward the sea",
    "Filling the toilet with butterscotch pudding",
    "Drinking from my priest's secret wine stash",
    "Eating together like a freaking family for once",
    "A long business meeting with no obvious purpose",
    "Twenty cheerleaders laughing when you stumble in the cafeteria",
    "Getting blasted in the face by a t-shirt cannon",
    "Taking down Santa with a surface-to-air missile",
    "A giant mechanical bird with a tragic backstory",
    "Driving into a tornado to learn about tornadoes",
    "How hot Orlando Bloom was in Lord of the Rings",
    "A micropig wearing a tiny raincoat and booties",
    "A snapping turtle biting the tip of your nose",
    "A ball of earwax  and toenail clippings",
    "A despondent Maple Leafs fan sitting all alone",
    "Waking up fully nude in a Milwaukee car park",
    "A sober Irishman who doesn't care for potatoes",
    "Getting caught by the police and going to jail",
    "The amount of baby carrots I can fit in my overnight bag",
    "Farting in class and hoping no one notices",
    "Running a few errands before saving the galaxy",
    "The events depicted in James Cameron's movie Avatar",
    "Filling every pouch of a utility belt with pizza",
    "A marriage-destroying game of trivia",
    "Getting drugs off the street and into my body",
    "Dark and mysterious forces beyond our control",
    "An inability to form meaningful relationships",
    "Changing a person's mind with logic and threats",
    "Two whales who aren't speaking to each other at the moment",
    "The peaceful and nonthreatening rise of China",
    "The full-blown marginalization of ugly people",
    "The good, hardworking people of Dubuque, Iowa",
    "Frantically writing equations on a chalkboard",
    "A Hungry-Man Frozen Christmas Dinner for One",
    "The violation of our most basic human rights",
    "Being a hideous beast that no one could love",
    "Staring at a painting and going 'hmmmmm...'",
    "Seeing a swarm of angry bees forming in the distance",
    "A chimpanzee in sunglasses",
    "The best, deepest quotes from Lost in Translation",
    "Feeling sad at the Old Country Buffet",
    "Feeding a man a pie made of sleeping mice",
    "The banks, the media, and just the entire system, man",
    "Eating all the skin off a rotisserie chicken",
    "The Quesadilla Explosion Salad from Chili's",
    "The sudden appearance of Jake from State Farm",
    "Figuring out how to play poker with a dolphin",
    "Becoming the President of the United States",
    "Having an awesome time drinking and driving",
    "How sad it will be when Morgan Freeman dies",
    "Discharging a firearm in a residential area",
    "An emergency all-floor meeting about inclusion",
    "Being chosen by God to win a free iPod Nano",
    "Dropping stuff and knocking everything over",
    "Pretty Pretty Princess Dress-Up Board Game",
    "Some punk kid who stole my turkey sandwich",
    "The inevitable death of the universe",
    "Going to a high school reunion dressed as Kermit",
    "An origami swan made out of expired bologna",
    "Wandering the streets in search of a swinger's party",
    "Google Glass and an e-cigarette, the ultimate combo",
    "A fully-dressed female videogame character",
    "Actually believing that the Bible happened",
    "A planet-devouring space worm named Rachel",
    "An exclusive partnership with Taylor Swift",
    "A hairless little jerk named Caillou",
    "The euphoric rush of getting an Amazon package",
    "Creamy slices of real, California avocado",
    "Going around pulling people's earbuds out",
    "Building a ladder of hot dogs to the moon",
    "Starting to see where ISIS is coming from",
    "Forgetting to eat, and consequently dying",
    "A table for one at The Cheesecake Factory",
    "A sobering quantity of chili cheese fries",
    "Dumb pomegranates that are hard to eat",
    "Funkified aliens from the planet Groovius",
    "An eight-foot man attempting to sleep on a six-foot sofa",
    "Brown paper packages tied up with string cheese",
    "Licking things to claim them as your own",
    "Filling my briefcase with business stuff",
    "Kourtney, Kim, Khloe, Kendall, and Kylie",
    "Telling a dumb story that goes nowhere",
    "Whoever the Prime Minister is these days",
    "A washing machine that leads to another dimension",
    "Roland the Farter, flautist to the king",
    "Crabapples all over the freaking sidewalk",
    "Grammar Nazis who are also regular Nazis",
    "A zero-risk way to make $2,000 from home",
    "Generally having no idea what's going on",
    "Almost giving money to a homeless person",
    "Painting with all the colors of the wind",
    "The fact that Hillary Clinton is a woman",
    "Greg Kinnear's terrible lightning breath",
    "The Celebrity Apprentice season finale",
    "The cool, refreshing taste of Coca-Cola",
    "More elephant poo than I bargained for",
    "The petty troubles of my neighbor Bill",
    "Horrifying laser hair removal accidents",
    "Ryan Gosling riding in on a white horse",
    "The endless sucking-up powers of Mike Pence",
    "Uncontrollable gas like you wouldn't believe",
    "A genetic predisposition for alcoholism",
    "Rubbing ketchup all over your bald head",
    "How strange it is to be anything at all",
    "Blossoming into a beautiful young woman with a terrible personality",
    "The full force of the American military",
    "Tender chunks of all-white-meat chicken",
    "Keeping the government out of my snooch",
    "Krampus, the Austrian Christmas monster",
    "Having a strong opinion about Obamacare",
    "Probably Grandma's last Christmas, kids",
    "How great of a pizza Jesus could probably make",
    "Getting drunk and watching Planet Earth",
    "The only gay person in a hundred miles",
    "Good-natured, fun-loving American racism",
    "Unlimited soup, salad, and breadsticks",
    "Throwing oranges at a man until he cries",
    "Three consecutive seconds of happiness",
    "The bond between a woman and her crippled horse",
    "A tiny fireman who puts out tiny fires",
    "A creepy child singing a nursery rhyme",
    "Small-town cops with military-grade assault rifles",
    "A three-foot-tall corned beef sandwich",
    "Drinking heavily while I watch the news",
    "A naked interactive theater thing my roommate dragged me to",
    "The dystopia we're living in right now",
    "How great of a movie Men in Black was",
    "What's left of the Great Barrier Reef",
    "A slightly crappier parallel universe",
    "Genetically engineered super-soldiers",
    "A sales team of clowns and Republicans",
    "Crying into the pages of Sylvia Plath",
    "Crying and running and eating spaghetti",
    "Irrefutable evidence that God is real",
    "Esmeralda, my most beautiful daughter, who unfortunately also wears Crocs",
    "Two terrible kids and a garbage husband",
    "A big ol' plate of fettuccine alfredo",
    "A slowly encroaching circle of wolves",
    "Awesome pictures of planets and stuff",
    "A Christmas stocking full of coleslaw",
    "The sound of my roommate crying",
    "A bachelor's degree in communications",
    "A big brain full of facts and sadness",
    "Trying to wake up from this nightmare",
    "Dancing carefree in white linen pants",
    "Fun and interesting facts about rocks",
    "Shiny gadgets to distract us from our chasm of sadness",
    "Destroying Dick Cheney's last horcrux",
    "A salad for men that's made of metal",
    "Getting crushed by a vending machine",
    "Tap dancing like there's no tomorrow",
    "Shutting up so I can watch the game",
    "Pumping out a baby every nine months",
    "Common-sense gun control legislation",
    "When the big truck goes 'Toot! Toot!'",
    "The mysterious fog rolling into town",
    "Defeating a gorilla in single combat",
    "Catching a live salmon in your mouth",
    "Growing up and becoming a Republican",
    "Five morons signing a lease together",
    "How many drinks Aunt Debbie has had",
    "The Hellman's Mayonnaise Corporation",
    "Forgetting to breathe and then dying",
    "Getting a cat instead of a boyfriend",
    "A tiny, less awesome guitar called a ukulele",
    "The screams... the terrible screams",
    "Crumbs all over the freaking carpet",
    "A vastly superior healthcare system",
    "Slapping Donald Trump over and over",
    "Mr. Squiggle, the Man from the Moon",
    "Buying the right clothes to be cool",
    "Some douche with an acoustic guitar",
    "Our first chimpanzee president",
    "A black-owned and operated business",
    "A shiny rock that proves I love you",
    "Prince Ali, fabulous he, Ali Ababwa",
    "The fear and hatred in men's hearts",
    "Pretending to have done the reading",
    "A little bit of schmutz right there",
    "A headache that's definitely cancer",
    "Water so cold it turned into a rock",
    "The quiet majesty of the sea turtle",
    "David Attenborough watching us mate",
    "Medieval Times Dinner & Tournament",
    "Punching a congressman in the face",
    "The entire Mormon Tabernacle Choir",
    "A middle-aged man on roller skates",
    "Sneezing in a laptop and closing it",
    "Just touching David Beckham's hair",
    "A cute, fuzzy koala with chlamydia",
    "Climbing into a kangaroo's pouch",
    "A six-point plan to stop the squirrels",
    "The shambling corpse of Larry King",
    "One unforgettable night of passion with Drew Carey",
    "An overwhelming variety of cheeses",
    "Beloved television star Bill Cosby",
    "Wearing glasses and sounding smart",
    "Finding a nice elevator to fart in",
    "Raising three kids on minimum wage",
    "Thinking about what eating even is",
    "Swapping bodies with mom for a day",
    "Blockbuster late fees up the wazoo",
    "Trying to feel something, anything",
    "The dying breath of the last human on earth",
    "An emotionally draining friendship",
    "Eating three sleeves of Chips Ahoy",
    "A stack of bunnies in a trenchcoat",
    "Your second cousin's second cousin",
    "Academy Award winner Meryl Streep",
    "Completely unwarranted confidence",
    "The Royal Canadian Mounted Police",
    "Queen Elizabeth's immaculate ankles",
    "A one-way ticket to Gary, Indiana",
    "Important news updates about Taylor Swift",
    "Going to bed at a reasonable hour",
    "Playing my nose like a trumpet",
    "Finding out that Santa isn't real",
    "The Great Lizard Uprising of the year 2352",
    "Wandering the desert for 40 years",
    "The spooky skeleton under my skin",
    "Three years' worth of toenail clippings in a shoebox",
    "A rooster's majestic morning crow",
    "Ringo Starr & His All-Starr Band",
    "An M. Night Shyamalan plot twist",
    "Breaking out into song and dance, only to realize you can't sing or dance",
    "My ugly face and bad personality",
    "Losing the kids in Walmart",
    "Throwing a virgin into a volcano",
    "All-you-can-eat shrimp for $8.99",
    "Passive aggressive Post-it notes",
    "An unstoppable wave of fire ants",
    "A sad, fat dragon with no friends",
    "A greased-up Matthew McConaughey",
    "Being popular and good at sports, but still hating yourself",
    "A crazy little thing called love",
    "Happy daddies with happy sandals",
    "A burrito that's just sour cream",
    "Film roles for actresses over 40",
    "Non-racist immigration reform",
    "Uggs, leggings, and a North Face",
    "This groovy new thing called LSD",
    "Getting slapped by Dr. Phil",
    "A belly full of hard-boiled eggs",
    "The inaudible screams of carrots",
    "A lifetime of internalized guilt",
    "A zombie with a tragic backstory",
    "A whole cheese pizza just for me",
    "The ability to talk to elephants",
    "German Chancellor Angela Merkel",
    "Former President George W. Bush",
    "A falcon with a cap on its head",
    "A homoerotic volleyball montage",
    "The way James Bond treats women",
    "Actually getting shot, for real",
    "The tiger that killed my father",
    "Whooping your butt at Mario Kart",
    "Sudden and unwanted slam poetry",
    "A cold and indifferent universe",
    "Founding a major world religion",
    "Slapping Ted Cruz until he's sterile",
    "A visually arresting turtleneck",
    "A falcon with a box on its head",
    "A boxing match with a giant box",
    "An extremely long elevator ride with a nervous farter",
    "Turn-of-the-century-sky racists",
    "A giant squid in a wedding gown",
    "That girl from the Hungry Games",
    "A protagonist with no redeeming qualities",
    "A prehistoric soup and salad bar",
    "A Super Soaker full of cat pee",
    "The Bachelorette season finale",
    "A Pringles can full of screams",
    "Seething with quiet resentment",
    "Giving birth to the Antichrist",
    "Solving problems with violence",
    "A disappointing birthday party",
    "Waking up in Idris Elba's arms",
    "Flying robots that kill people but also sort their recycling properly",
    "The best taquito in the galaxy",
    "A constant need for validation",
    "The black half of Barack Obama",
    "10,000 shrieking teenage girls",
    "Doing a somersault and barfing",
    "Valuable leadership experience with absolutely no financial benefit",
    "Punching a tree to gather wood",
    "Absolutely destroying a pair of new underwear",
    "Achieving reproductive success",
    "3.7 billion years of evolution",
    "An evening with Michael Buble",
    "The mere concept of Applebee's",
    "How fun it is to eat Pringles",
    "J.D. Power and his associates",
    "The true meaning of Christmas",
    "Stephen Hawking talking dirty",
    "Filling my son with spaghetti",
    "Moderate-to-severe joint pain",
    "Robots who just want to party",
    "The body of a 46-year-old man",
    "Salsa Night at Dave's Cantina",
    "Falling into a pit of waffles",
    "Waking up inside of a tornado",
    "Cool 90's up-in-the-front hair",
    "Rock music and premarital sex",
    "Father's forbidden chocolates",
    "Sacrificing Isaac to the Lord",
    "A sandwich with Cheetos in it",
    "Eerie music in a horror movie",
    "An old guy who's almost dead",
    "Spontaneous human combustion",
    "Fading away into nothingness",
    "Mutually assured destruction",
    "Accepting the way things are",
    "Burning down the White House",
    "Women in yoghurt commercials",
    "Wearing an octopus for a hat",
    "Going around punching people",
    "Boris the Soviet Love Hammer",
    "Neil Diamond's Greatest Hits",
    "A peyote-fueled vision quest",
    "A hopeless amount of spiders",
    "Having been dead for a while",
    "Giant geckos from outer space",
    "A duffel bag full of lizards",
    "All these people I've killed",
    "Slicing ham in icy silence",
    "Gift-wrapping a live hamster",
    "The fleetingness of all things",
    "Shooting a wizard with a gun",
    "The all-seeing Eye of Sauron",
    "My uncle who voted for Trump",
    "Saving 20% or more on khakis",
    "An 800-foot-long pool noodle",
    "Whatever a McRib is made of",
    "The Three-Fifths Compromise",
    "Explaining how vaginas work to children",
    "Eating the last known bison",
    "Massive, widespread drought",
    "An evil man in evil clothes with an evil minion gerbil",
    "A surprising amount of hair",
    "A fortuitous turnip harvest",
    "Special musical guest, Cher",
    "My boyfriend's stupid mustache",
    "Whomsoever let the dogs out",
    "Taking the form of a falcon",
    "Assassinating the president",
    "Doritos and a Fruit Roll-Up",
    "Conservative talking points",
    "Falling in love with a beautiful chicken",
    "A hazmat suit full of farts",
    "The sun engulfing the earth",
    "Goats screaming like people",
    "Matching with mom on Tinder",
    "A mailbox full of scorpions",
    "A windmill full of turtles",
    "NBA superstar LeBron James",
    "Getting a DUI on a Zamboni",
    "Your sister's prosthetic leg",
    "Total control of the media",
    "The day the birds attacked",
    "The power of the Dark Side",
    "A mouthful of potato salad",
    "Owls, the perfect predator",
    "The ghost of Marlon Brando",
    "My dad's dumb face",
    "A self-microwaving burrito",
    "Gwyneth Paltrow's opinions",
    "Russian super-tuberculosis",
    "Being turned into sausage",
    "A toxic family environment",
    "A mysterious, floating orb",
    "The spicy chicken sandwich from Popeyes",
    "Dwayne 'The Rock' Johnson",
    "The Boy Scouts of America",
    "The wonders of the Orient",
    "The disgusting miracle of childbirth",
    "Selling drugs to children",
    "Radical Mormon terrorism",
    "A literal tornado of fire",
    "The boner of the elderly",
    "A PowerPoint presentation",
    "One ring to rule them all",
    "Walking into a glass door",
    "Child Protective Services",
    "Whatever you wish, mother",
    "Like a million alligators",
    "Not believing in giraffes",
    "A woman's right to choose",
    "Eternal screaming madness",
    "How good lead paint tastes",
    "Starting a useless podcast",
    "Bad emotions I don't want",
    "Carbon monoxide poisoning",
    "Being replaced by a robot",
    "Feeling bloaty and crampy and wanting to murder the mailman",
    "Subsisting on pizza bagels",
    "Hillary Clinton's emails",
    "Farting and walking away",
    "Teaching a robot to love",
    "Classy sex with Patrick Stewart",
    "Bill Nye the Science Guy",
    "Strong female characters",
    "The Underground Railroad",
    "Skippy the drunken Bush Kangaroo",
    "Indescribable loneliness",
    "Having shotguns for legs",
    "Breaking the kneecaps of the Harlem Globetrotters",
    "A spontaneous conga line",
    "Crippling social anxiety",
    "My brother's hot friends",
    "Self-identifying as a DJ",
    "Daddy going away forever",
    "A gun that shoots cobras",
    "Eating an entire snowman",
    "Feeling lots of feelings",
    "Beep beep boop beep boop",
    "Being the absolute worst",
    "Unbelievably soft carpet on your bum",
    "Game of Thrones spoilers",
    "A whole thing of butter",
    "A crap-ton of almonds",
    "Selling dandelions to gullible children",
    "Weapons-grade plutonium",
    "A cop who is also a dog",
    "Destroying the evidence",
    "Loki, the trickster god",
    "Bosnian chicken farmers",
    "Falling into the toilet and liking the feeling",
    "Unquestioning obedience",
    "Being a terrible father",
    "A giant powdery manbaby",
    "Tiny, rancid girl farts",
    "Some real spicy shrimps",
    "Crushing the patriarchy",
    "An army of Michael Keatons",
    "An outbreak of smallbox",
    "Futuristic death sports",
    "World Wars 3 through 5",
    "That one leftover screw",
    "Failing the Turing test",
    "A good, strong gorilla with perfect teeth",
    "10,000 Syrian refugees",
    "Inappropriate yodeling",
    "Unfathomable stupidity",
    "An AR-15 assault rifle",
    "Sweet, sweet vengeance",
    "Morgan Freeman's voice",
    "Contagious face cancer",
    "Eugene Levy's eyebrows",
    "Millions of cane toads",
    "The Hemsworth brothers",
    "Denying climate change",
    "Spending lots of money on etsy",
    "A mime having a stroke",
    "Having $57 in the bank",
    "One thousand Slim Jims",
    "The black Power Ranger",
    "24-hour media coverage",
    "A dollop of sour cream",
    "The harsh light of day",
    "Writing IOU's for child support payments",
    "Gregor, my largest son",
    "Hating Hillary Clinton",
    "The Bowflex Revolution",
    "Xena, Warrior Princess",
    "President Donald Trump",
    "Post-partum depression",
    "A monkey taking a bath in your kitchen sink",
    "Selling a goat on ebay",
    "My Uber driver, Pavel",
    "The homosexual agenda",
    "Flesh-eating bacteria",
    "Child beauty pageants",
    "Waiting until marriage",
    "A lifetime of sadness",
    "Dead birds everywhere",
    "Sunshine and rainbows",
    "Extremely tight pants",
    "An oversized lollipop",
    "Arnold Schwarzenegger",
    "Living in Alabama",
    "Blowing up Washington D.C. and starting from scratch",
    "Suggestively winking at old people",
    "The World of Warcraft",
    "Rising from the grave",
    "Some kind of bird-man",
    "Living in a trash can",
    "A plunger to the face",
    "Mad hacky-sack skills",
    "My manservant, Claude",
    "All the single ladies",
    "Ripping a dog in half",
    "Interspecies marriage",
    "A disappointing salad",
    "Getting high with mom",
    "Political correctness",
    "A woman's perspective",
    "Denying the Holocaust",
    "Tommy, the teen mayor",
    "Black lives mattering",
    "Immaculate conception",
    "Boxing up my feelings like a man",
    "A world without boxes",
    "A joyless vegan patty",
    "An empty wishing well",
    "Seeing my father cry",
    "A bag of magic beans",
    "Harry Potter erotica",
    "The literal heart of a child",
    "Becoming a blueberry",
    "Lumberjack fantasies",
    "Elderly Japanese men",
    "Adorable orphans who will never get adopted",
    "Soup that is too damn hot",
    "Benedict Cumberbatch",
    "The smell of middle school boys after gym class",
    "Mufasa's death scene",
    "Chugging a lava lamp",
    "Insatiable bloodlust",
    "Bouncing up and down",
    "Being nine years old",
    "A horse with no legs",
    "Making out and stuff",
    "Shouting the loudest",
    "200 years of slavery",
    "Reading Internet comments",
    "Making Islam illegal",
    "At least three ducks",
    "Vigorous jazz hands",
    "Making a pouty face",
    "Peeing a little bit",
    "Saying 'I love you.'",
    "Fragile masculinity",
    "The Blood of Christ",
    "Chainsaws for hands",
    "Jehovah's Witnesses",
    "Taking a sheep-wife",
    "Converting to Islam",
    "Children on leashes",
    "Neil Patrick Harris",
    "Syphilitic insanity",
    "The passage of time",
    "What Jesus would do",
    "Mom's new boyfriend",
    "Loud, scary thunder",
    "Late-stage dementia",
    "Who really did 9/11",
    "Kurt Cobain's death",
    "Another shitty year",
    "The Boxcar Children",
    "Thy neighbor's wife",
    "Switching to Geico",
    "An Oedipus complex",
    "Pretending to care",
    "Being marginalized",
    "Illegal immigrants",
    "Your weird brother",
    "The American Dream",
    "The Trail of Tears",
    "Germans on holiday",
    "Stockholm Syndrome",
    "A sweet-ass spaceship",
    "Demonic possession",
    "Vietnam flashbacks",
    "Vegetarian options",
    "Free ice cream from a windowless van",
    "Genghis Khan's DNA",
    "P.F. Chang himself",
    "Meatloaf, the food",
    "Objectifying women",
    "An empowered woman",
    "The LGBT community",
    "A box inside a box",
    "Slowly evaporating",
    "My browser history",
    "Smallpox blankets",
    "The Wi-Fi password",
    "Poor life choices",
    "Natural selection",
    "Teenage pregnancy",
    "Jennifer Lawrence",
    "A really cool hat that my mom bought me",
    "The glass ceiling",
    "Object permanence",
    "Alcohol poisoning",
    "The Great Emu War",
    "All of this blood",
    "Samuel L. Jackson",
    "A Ugandan warlord",
    "Exploding pigeons",
    "Meatloaf, the man",
    "Rocking a 1.5 GPA",
    "Underage drinking",
    "Young Republicans",
    "Active listening",
    "Police brutality",
    "The Kool-Aid Man",
    "Opposable thumbs",
    "Spaghetti? Again?",
    "A mopey zoo lion",
    "Women's suffrage",
    "Flightless birds",
    "Old-people smell",
    "Judging everyone",
    "Canadian Netflix",
    "Nothing but sand and garbage",
    "Robert Downey, Jr.",
    "Being a shy dinosaur",
    "Eating an albino goat",
    "Survivor's guilt",
    "Oncoming traffic",
    "Racial profiling",
    "How awesome I am",
    "Crazy opium eyes",
    "Sharks with legs",
    "My worthless son",
    "Condoleezza Rice",
    "Watching you die",
    "Microaggressions",
    "Space Jam on VHS",
    "Eternal darkness",
    "Kevin Bacon Bits",
    "Oreos for dinner",
    "Dividing by zero",
    "Too many edibles",
    "YouTube comments",
    "White privilege",
    "Kamikaze pilots",
    "Powerful thighs",
    "Finger painting",
    "Spectacular abs that I wanna lick mayo off of",
    "My inner demons",
    "William Shatner",
    "The Black Death",
    "Mad cow disease",
    "Michael Jackson",
    "Moral ambiguity",
    "Grandpa's ashes",
    "Homeless people",
    "Suicide bombers",
    "Hot doooooooogs!",
    "My first period",
    "Backwards knees",
    "Gender equality",
    "Mario Kart rage",
    "Whoopi Goldberg",
    "A sprightly jig",
    "The Hamburglar",
    "Vladimir Putin",
    "Menstrual rage",
    "Drinking alone",
    "Raptor attacks",
    "AXE Body Spray",
    "Crippling debt",
    "Justin Trudeau",
    "Somali pirates",
    "Rupert Murdoch",
    "Nunchuck moves",
    "The Dalai Lama",
    "The freakshow that is the human body",
    "Fake news",
    "Such a big boy",
    "Dumpster juice",
    "A black friend",
    "Mental illness",
    "A liberal bias",
    "Jiggle physics",
    "Endless ninjas",
    "Nuclear winter",
    "Being a woman",
    "Laying an egg during Jeopardy",
    "Ronald Reagan",
    "Justin Bieber",
    "Being on fire",
    "Racist Oompa-Loompas",
    "A crucifixion",
    "Polish people",
    "A wombat with tummy troubles",
    "Grave robbing",
    "My first kill",
    "Finding Waldo",
    "Jeff Goldblum",
    "Dorito breath",
    "Eating delicious people",
    "Wendy from HR",
    "Day-old tacos",
    "Hospice care",
    "A tiny horse",
    "Doing crimes",
    "Dead parents",
    "Nicolas Cage",
    "Daddy issues",
    "The Big Bang",
    "White people",
    "Mansplaining",
    "Brown people",
    "Steve Bannon",
    "The Russians",
    "Sperm whales",
    "Danny DeVito",
    "Tiny nipples",
    "Women voting",
    "Gay thoughts",
    "Libertarians",
    "Space racism",
    "Fancy Feast",
    "Scientology",
    "Dead babies",
    "Emma Watson",
    "Bisexuality",
    "Poor people",
    "Republicans",
    "The Rapture",
    "MegaHitler",
    "Fiery poops",
    "The milkman",
    "Trench foot",
    "Being white",
    "Kim Jong-un",
    "Being black",
    "Miley Cyrus",
    "White power",
    "Santa Claus",
    "Hot lettuce",
    "Child labor",
    "Moon people",
    "Lunchables",
    "Land mines",
    "Alcoholism",
    "Mike Pence",
    "Wet dreams",
    "Horse meat",
    "Kanye West",
    "The French",
    "Xenophobia",
    "Tom Cruise",
    "Eating ass",
    "A sad mall Santa",
    "Kale farts",
    "The Amish",
    "The South",
    "Many bats",
    "The Indian flute",
    "Blackface",
    "A manhole",
    "Menopause",
    "Vegemite",
    "Adderall",
    "Facebook",
    "Fox News",
    "The gays",
    "The Pope",
    "Swooping",
    "Your mom",
    "Hipsters",
    "Feminism",
    "Chipotle",
    "Misogyny",
    "Beyonce",
    "The KKK",
    "Leprosy",
    "Bananas",
    "Grandma",
    "Puberty",
    "A basket full of puppies",
    "My soul",
    "RoboCop",
    "Boogers",
    "Poverty",
    "England",
    "A shark",
    "Gandalf",
    "Velcro",
    "Viagra",
    "GoGurt",
    "Batman and Robin",
    "Famine",
    "Racism",
    "Fat Gandhi",
    "Ghosts",
    "Stalin",
    "Brexit",
    "Mooing",
    "Quiche",
    "Khakis",
    "A fart",
    "Africa",
    "Cancer",
    "Uranus",
    "Geese",
    "Oprah",
    "Hobos",
    "Nazis",
    "Jesus",
    "Jafar",
    "Shaft",
    "Clams",
    "Daddy",
    "Texas",
    "China",
    "Ebola",
    "Hodor",
    "Bees?",
    "AIDS",
    "PTSD",
    "ISIS",
    "Guns",
    "Corn",
    "Men",
    "God",
    "Mom",
    "Jeb!"
    ]

    private promptCardsUnshuffled = [
    "(Heavy breathing) Luke, I am ____.",
    "____. Awesome in theory, kind of a mess in practice.",
    "____. Betcha can't have just one!",
    "____. High five, bro.",
    "____. It's a trap!",
    "____. Once you pop, the fun don't stop!",
    "____: Hours of fun for the whole family!",
    "____: kid-tested, mother-approved.",
    "____? Jim'll fix it!",
    "____? Yeah, nah.",
    "50% of all marriages end in ____.",
    "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ____.",
    "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to: ____.",
    "A remarkable new study shows that chimps have evolved their own primitive version of ____.",
    "A romantic, candlelit dinner would be incomplete without ____.",
    "A study published in Nature this week found that ____ is good for you in small doses.",
    "A successful job interview begins with a firm handshake and ends with ____.",
    "A wise man said, 'Everything is about sex. Except sex. Sex is about ____.'",
    "According to Arizona's stand-your-ground law, you're allowed to shoot someone if they're ____.",
    "After blacking out during New Year's Eve, I was awoken by ____.",
    "After months of practice, I think I'm finally ready for ____.",
    "Airport security guidelines now prohibit ____ on airplanes.",
    "All classes today are canceled due to ____.",
    "Alternative medicine is now embracing the curative powers of ____.",
    "America is hungry. America needs ____.",
    "America’s next new reality show features eight washed-up celebrities living with ____.",
    "And I would have gotten away with it, too, if it hadn't been for ____!",
    "And in the end, the dragon was not evil; he just wanted ____.",
    "And today's soup is Cream of ____.",
    "And what did you bring for show and tell?",
    "And would you like those buffalo wings mild, hot, or ____?",
    "Arby's: We have ____.",
    "Armani suit: $1,000. Dinner for two: $300. The look on her face when you surprise her with ____: priceless.",
    "Art isn't just a painting in a stuffy museum. Art is alive. Art is ____.",
    "As king, how will I keep the peasants in line?",
    "As part of his daily regimen, Anderson Cooper sets aside 15 minutes for ____.",
    "As reparations for slavery, all African Americans will receive ____.",
    "As Teddy Roosevelt said, the four manly virtues are honor, temperance, industry, and ____.",
    "As the mom of five rambunctious boys, I'm not stranger to ____.",
    "Astronomers have discovered that the universe consists of 5% ordinary matter, 25% dark matter, and 70% ____.",
    "Aw babe, your burps smell like ____!",
    "Aww, sick! I just saw this skater do a 720 kickflip into ____!",
    "Because you enjoyed Tiger King, we thought you might like ____.",
    "Before television, all we had was ____.",
    "Behind every powerful man is ____.",
    "Behold the Four Horsemen of the Apocalypse! War, Famine, Death, and ____.",
    "Believe it or not, Jim Carrey can do a dead-on impression of ____.",
    "Best you go back where you came from, now. We don't take too kindly to ____ in these parts.",
    "BowWOW is the first pet hotel in L.A. that offers ____ for dogs.",
    "Brought to you by Budweiser, the Official Beer of ____.",
    "But before I kill you, Mr. Bond, I must show you ____.",
    "But wait, there's more! If you order in the next 15 minutes, we'll throw in ____ for free!",
    "Call the law offices of Goldstein Goldstein, because no one should have to tolerate ____ in the workplace.",
    "Can a woman really have it all? A career and ____?",
    "Cancel all my meetings. We've got a situation with ____ that requires my immediate attention.",
    "Can't you see? The Jews are behind everything--the banks, the media, even ____!",
    "Charades was ruined for me forever when my mom had to act out ____.",
    "Check me out, yo! I call this dance move '____.'",
    "CNN breaking news! Scientists discover ____.",
    "Computer! Display ____ on screen. Enhance.",
    "Crikey! I've never seen ____ like this before! Let's move in for a closer look.",
    "Critics are raving about HBO's new Game of Thrones spin-off, 'Game of ____.'",
    "Daddy, why is mommy crying?",
    "Dammit, Gary. You can't just solve every problem with ____.",
    "Dance like there's nobody watching, love like you'll never be hurt, and live like you're ____.",
    "Dear Abby, I'm having some trouble with ____ and would like your advice.",
    "Dear Leader Kim Jong-un, our village praises your infinite wisdom with a humble offering of ____.",
    "Dear Mom and Dad, Camp is fun. I like capture the flag. Yesterday, one of the older kids taught me about ____.",
    "Did you know? Our college was recently named the #1 school for ____!",
    "Do the Dew with our most extreme flavor yet! Get ready for Mountain Dew ____!",
    "Do you lack energy? Does it sometimes feel like the whole world is ____? Ask your doctor about Zoloft.",
    "Doctor, you've gone too far! The human body wasn't meant to withstand that amount of ____!",
    "Donald Trump has nominated ____ for his VP.",
    "Donald Trump's first act as president was to outlaw ____.",
    "Donna, please pick up my dry cleaning and get my wife something for Christmas. I think she likes ____.",
    "Don't forget! Beginning this week, Casual Friday will officially become '____ Friday.'",
    "Don't miss Rachel Ray's hit new show, Cooking with ____.",
    "Don't worry, kid. It gets better. I've been living with ____ for 20 years.",
    "Dude, do not go in that bathroom. There's ____ in there.",
    "During high school, I never really fit in until I found ____ club.",
    "During his midlife crisis, my dad got really into ____.",
    "During sex, I like to think about ____.",
    "Errbody in the club ____.",
    "Every Christmas, my uncle gets drunk and tells the story about ____.",
    "Everyone is staring at you because you're ____.",
    "Excuse me, waiter. Could you take this back? This soup tastes like ____.",
    "Fear leads to anger. Anger leads to hate. Hate leads to ____.",
    "Feeling so grateful! #amazing #mylife #____",
    "Finally! A service that delivers ____ right to your door.",
    "For my turn, I will spend four gold and allocate all three workers to ____.",
    "Future historians will agree that ____ marked the beginning of America's decline.",
    "Girls just wanna have ____.",
    "Google Calendar alert: ____ in 10 minutes.",
    "Having the worst day EVER. #____",
    "Having tired of poetry and music, the immortal elves now fill their days with ____.",
    "Help me doctor, I've got ____ up my nose.",
    "Here at the Academy for Gifted Children, we allow students to explore ____ at their own pace.",
    "Here is the church, here is the steeple, open the doors, and there is ____.",
    "Hey baby, come back to my place and I'll show you ____.",
    "Hey guys, welcome to Boston Pizza! Would you like to start the night off right with ____?",
    "Hey guys, welcome to Chili's! Would you like to start the night off right with ____?",
    "Hey kids! Put on your lab coats and strap on your safety goggles, because today we're learning about ____!",
    "Hey Reddit! I'm ____. Ask me anything.",
    "Hey, whatever happened to Renee Zellweger?",
    "Hey, you guys want to try this awesome new game? It's called ____.",
    "Hi MTV! My name is Kendra, I live in Malibu, I'm into ____, and I love to have a good time.",
    "Hi, this is Jim from accounting. We noticed a $1,200 charge labeled '____.' Can you explain?",
    "Honey, Mommy and Daddy love you very much. But apparently Mommy loves ____ more than she loves Daddy.",
    "Housekeeping! You want ____?",
    "How am I maintaining my relationship status?",
    "How did I lose my virginity?",
    "How did Stella get her groove back?",
    "I can't believe Netflix is using ____ to promote House of Cards.",
    "I don't believe in God. I believe in ____.",
    "I don't know exactly how I got the PAX plague, but I suspect it had something to do with ____.",
    "I don't mean to brag, but they call me the Michael Jordan of ____.",
    "I drink to forget ____.",
    "I get by with a little help from ____.",
    "I got 99 problems but ____ ain't one.",
    "I have a strict policy. First date, dinner. Second date, kiss. Third date, ____.",
    "I have an idea even better than Kickstarter, and it's called ____-starter.",
    "I know when that hotline bling, that can only mean one thing: ____.",
    "I learned the hard way that you can't cheer up a grieving friend with ____.",
    "I love being a mom. But it's tough when my kids come home filthy from ____.",
    "I really hope my grandma doesn't ask me to explain ____ again.",
    "I spent my whole life working toward ____.",
    "I work my ass off all day for this family, and this is what I come home to? ____!?",
    "If at first you don't succeed, try ____.",
    "If God didn't want us to enjoy ____, he wouldn't have given us feet.",
    "If you can't be with the one you love, love ____.",
    "If you like ____, you might be a redneck.",
    "I'm a bitch, I'm a lover, I'm a child, I'm ____.",
    "I'm Bobby Flay, and if you can't stand ____, get out of the kitchen!",
    "I'm going on a cleanse this week. Nothing but kale juice and ____.",
    "I'm just gonna stay in tonight. You know, Netflix and ____.",
    "I'm LeBron James, and when I'm not slamming dunks, I love ____.",
    "I'm no doctor, but I'm pretty sure what you're suffering from is called '____.'",
    "I'm not going to lie. I despise ____. There, I said it.",
    "I'm not like the rest of you. I'm too rich and busy for ____.",
    "I'm pretty sure I'm high right now, because I'm absolutely mesmerized by ____.",
    "I'm sorry, Professor, but I couldn't complete my homework because of ____.",
    "I'm sorry, sir, but I couldn't complete my homework because of ____.",
    "I'm sorry, sir, but we don't allow ____ at the country club.",
    "I'm sorry, sir, but your insurance plan doesn't cover injuries caused by ____.",
    "In 2019, Donald Trump eliminated our national parks to make room for ____.",
    "In a pinch, ____ can be a suitable substitute for milk.",
    "In Australia, ____ is twice as big and twice as deadly.",
    "In Belmarsh Prison, word is you can trade 200 cigarettes for ____.",
    "In bourgeois society, capital is independent and has individuality, while the living person is ____.",
    "In his farewell address, George Washington famously warned Americans about the dangers of ____.",
    "In his new action comedy, Jackie Chan must fend off ninjas while also dealing with ____.",
    "In his new self-produced album, Kanye West raps over the sounds of ____.",
    "In his newest and most difficult stunt, David Blaine must escape from ____.",
    "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated ____.",
    "In return for my soul, the Devil promised me ____.",
    "In Rome, there are whisperings that the Vatican has a secret room devoted to ____.",
    "In the 1950s, psychologists prescribed ____ as a cure for homosexuality.",
    "In the beginning, there was darkness. And the Lord said, 'Let there be ____.'",
    "In the new Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time.",
    "In the seventh circle of Hell, sinners must endure ____ for all eternity.",
    "In this paper, I will explore ____ from a feminist perspective.",
    "In what's being hailed as a major breakthrough, scientists have synthesized ____ in the lab.",
    "Introducing X-treme Baseball! It's like baseball, but with ____!",
    "It lurks in the night. It hungers for flesh. This summer, no one is safe from ____.",
    "It's a pity that kids these days are all getting involved with ____.",
    "It's beginning to look a lot like ____.",
    "It's Morphin' Time! Mastodon! Pterodactyl! Triceratops! Sabretooth Tiger! ____!",
    "It's not delivery. It's ____.",
    "I've got rhythm, I've got music, I've got ____. Who could ask for anything more?",
    "I've had a horrible vision, father. I saw mountains crumbling, stars falling from the sky. I saw ____.",
    "James is a lonely boy. But when he discovers a secret door in his attic, he meets a magical new friend: ____.",
    "Jesus is ____.",
    "Just once, I'd like to hear you say 'Thanks, Mom. Thanks for ____.'",
    "Just saw this upsetting video! Please retweet!! #stop____",
    "Kids these days with their iPods and their internet. In my day, we all needed to pass the time was ____.",
    "Kids, I don't need drugs to get high. I'm high on ____.",
    "Legend has it, Prince wouldn't perform without ____ in his dressing room.",
    "Legend tells of a princess who has been asleep for a thousand years and can only be awoken by ____.",
    "Life would be woefully incomplete without ____.",
    "Life's pretty tough in the fast lane. That's why I never leave the house without ____.",
    "Lifetime presents 'The Heartwarming Story of ____.'",
    "Listen, Gary, I like you. But if you want that corner office, you're going to have to show me ____.",
    "Listen, son. If you want to get involved with ____, just be cautious.",
    "Little Miss Muffet, sat on a tuffet, eating her curds and ____.",
    "Looking to earn big bucks? Learn how to make ____ work for you!",
    "Lovin' you is easy 'cause you're ____.",
    "LSD + ____ = really bad time.",
    "Madam President, the asteroid is headed directly for Earth and there's one one thing that can stop it: ____.",
    "Man, this is bull. F*** ____.",
    "Maybe she's born with it. Maybe it's ____.",
    "Members of New York's social elite are paying thousands of dollars just to experience ____.",
    "Men's Wearhouse. You're gonna like ____. I guarantee it.",
    "Military historians remember Alexander the Great for his brilliant use of ____ against the Persians.",
    "Mom's to-do list: Buy groceries. Clean up ____. Soccer practice.",
    "Money can't buy me love, but it can buy me ____.",
    "Most Americans would not vote for a candidate who is openly ____.",
    "My country, 'tis of thee, sweet land of ____.",
    "My fellow Americans: Before this decade is out, we will have ____ on the moon!",
    "My gym teacher got fired for adding ____ to the obstacle course.",
    "My memory of last night is pretty hazy. I remember ____ and that's pretty much it.",
    "My mom freaked out when she looked at my browser history and found ____.com.",
    "My mom will never be the same after ____.",
    "My name is Inigo Montoya. You killed my father. Prepare for ____.",
    "My new favorite porn star is Joey '____' McGee.",
    "My plan for world domination begins with ____.",
    "NASA will spend 15 billion dollars on an unprecedented mission: ____ in space.",
    "New from Mattel, it's ____ Barbie!",
    "Next from J.K. Rowling: Harry Potter and the Chamber of ____.",
    "Next on ESPN2: The World Series of ____.",
    "Next time on Dr. Phil: How to talk to your child about ____.",
    "Next week on the Discovery Channel, one man must survive the depths of the Amazon with only ____ and his wits.",
    "Nicholas Cage was most famous for his ____.",
    "No, no, no, no, no, NO! I will NOT let ____ ruin this wedding.",
    "Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and ____.",
    "Nothing says 'I love you' like ____.",
    "Now at the Natural History Museum: an interactive exhibit on ____.",
    "Now in bookstores: 'The Audacity of ____,' by Barack Obama.",
    "O Canada, we stand on guard for ____.",
    "Oh no! Siri, how do I fix ____?",
    "Oh, your daughter should meet my son! He gives to charity, he loves ____ and did I mention he's a doctor?",
    "Okay here's the pitch. James Franco and Seth Rogen are trying to score some weed, and then ____ happens.",
    "Old Macdonald had ____. E-I-E-I-O.",
    "On the third day of Christmas, my true love gave to me: three French hens, two turtle doves, and ____.",
    "One more thing. Watch out for Big Mike. They say he killed a man with ____.",
    "Only two things in life are certain: death and ____.",
    "Our relationship is strictly professional. Let's not complicate things with ____.",
    "Patient presents with swollen fingers and toes. Likely a result of ____.",
    "Penalty! ____: that's 5 minutes in the box!",
    "Please look at this Rorschach test. What do you see?",
    "Pledges! Time to prove you're Delta Phi material. Chug this beer, take off your shirts, and get ready for ____.",
    "Poor Brandon, still living in his parents' basement. I hear he never got over ____.",
    "Press # to unleash ____.",
    "Revealed: Why He Really Resigned! Pope Benedict's Secret Struggle with ____!",
    "Run, run, as fast as you can! You can't catch me, I'm ____!",
    "Science will never explain ____.",
    "Senator, I trust you enjoyed ____ last night. Now, can I count on your vote?",
    "She's a lady in the streets, ____ in the sheets.",
    "She's just one of the guys, you know? She likes beer, and football, and ____.",
    "Sir, we found you passed out naked on the side of the road. What's the last thing you remember?",
    "Summer lovin', had me a blast. ____, happened so fast.",
    "Tampax: Don't let your period ruin ____.",
    "The blind date was going horrible until we discovered our shared interest in ____.",
    "The Chevy Tahoe. With the power and space to take ____ everywhere you go.",
    "The class field trip was completely ruined by ____.",
    "The Department of Psychology is looking for paid research volunteers. Are you 18-25 and suffering from ____?",
    "The door swings open and she walks in, legs up to here. Something in her eyes tells me she's looking for ____.",
    "The elders of the Ibo tribe of Nigeria recommend ____ as a cure for impotence.",
    "The Five Stages of Grief: denial, anger, bargaining, ____, acceptance.",
    "The healing process began when I joined a support group for victims of ____.",
    "The Japanese have developed a smaller, more efficient version of ____.",
    "The new Chevy Tahoe. With the power and space to take ____ everywhere you go.",
    "The only thing worse than the coronavirus is ____.",
    "The secret to a lasting marriage is communication, communication, and ____.",
    "The U.S. government has funneled millions of dollars into research on ____.",
    "The Westboro Baptist Church is now picketing soldiers' funerals with signs that read 'GOD HATES ____!'",
    "Then the princess kissed the frog, and all of a sudden the frog was ____!",
    "There is no God. It's just ____ and then you die.",
    "This app is basically Tinder, but for ____.",
    "This Friday at the Liquid Lounge, it's ____ Night! Ladies drink free.",
    "This holiday season, Tim Allen must overcome his fear of ____ to save Christmas.",
    "This is America. If you don't work hard, you don't succeed. I don't care if you're black, white, purple, or ____.",
    "This is the prime of my life. I'm young, hot, and full of ____.",
    "This is the third time my son has been sent to the principal's office for ____.",
    "This is the way the world ends. Not with a bang, but with ____.",
    "This is your captain speaking. Fasten your seatbelts and prepare for ____.",
    "This month's Cosmo: 'Spice up your sex life by bringing ____ into the bedroom.'",
    "To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of ____.",
    "Today on Jerry Springer: 'Help! My son is ____!'",
    "Today on Mythbusters, we find out how long ____ can withstand repeated explosions.",
    "Tonight's top story: What you don't know about ____ could kills you.",
    "TRIGGER WARNING: ____.",
    "Trump's great! Trump's got ____. I love that.",
    "Turns out that ____-Man was neither the hero we needed nor wanted.",
    "Uh, hey guys, I know this was my idea, but I'm having serious doubts about ____.",
    "Unfortunately, Neo, no one can be told what ____ is. You have to see it for yourself.",
    "Up next on Nickelodeon: 'Clarissa Explains ____.'",
    "Wait, I came here to buy socks. How did I wind up with ____?",
    "Wake up, America. Christmas is under attack by secular liberals and their ____.",
    "War! What is it good for?",
    "We do not shake with our left hands in this country. That is the hand we use for ____.",
    "We never did find ____, but along the way we sure learned a lot.",
    "We were the best hand-to-hand combatants on the ship. I had reach, but she had ____.",
    "Well if ____ is a crime, then lock me up!",
    "Well if ____ is good enough for Oprah, it's good enough for me.",
    "Well if you'll excuse me, gentlemen, I have a date with ____.",
    "We're not like other news organizations. Here at Slugline, we welcome ____ in the office.",
    "Wes Anderson's new film tells the story of a precocious child coming to terms with ____.",
    "What are all those whales singing about?",
    "What are my parents hiding from me?",
    "What broke up the original Wiggles?",
    "What brought the baptism to a grinding halt?",
    "What did I bring back from Amsterdam?",
    "What did I bring back from Bali?",
    "What ended my last relationship?",
    "What gives me uncontrollable gas?",
    "What has been making life difficult at the nudist colony?",
    "What is Batman's guilty pleasure.",
    "What is George W. Bush thinking about right now?",
    "What is the answer to life, the universe, and everything?",
    "What keeps me warm during the freezing cold winter?",
    "What killed my grandma?",
    "What left this stain on my couch?",
    "What made my first kiss so awkward?",
    "What made Spock cry?",
    "What makes life worth living?",
    "What never fails to liven up the party?",
    "What really killed the dinosaurs?",
    "What turned me into a Republican?",
    "What will always get you laid?",
    "What will end racism once and for all?",
    "What would grandma find disturbing, yet oddly charming?",
    "What's a girl's best friend?",
    "What's about to take this dance floor to the next level?",
    "What's fun until it gets weird?",
    "What's harshing my mellow, man?",
    "What's making things awkward in the sauna?",
    "What's my secret power?",
    "What's so important right now that you can't call your mother?",
    "What's Teach For America using to inspire inner city students to succeed?",
    "What's that smell?",
    "What's that sound?",
    "What's the latest bullshit that's troubling this quaint fantasy town?",
    "What's the next Happy Meal toy?",
    "What's there a ton of in heaven?",
    "What's wrong with these gorillas?",
    "When I am a billionaire, I shall erect a 20-metre statue to commemorate ____.",
    "When I am Prime Minister of the United Kingdom, I will create the Ministry of ____.",
    "When I was a kid, we used to play Cowboys and ____.",
    "When I’m the president, I will create the Department of ____.",
    "When my grandfather came to this country, all he had was the shoes on his feet and ____.",
    "When Pharaoh remained unmoved, Moses called down a Plague of ____.",
    "When you go to the polls on Tuesday, remember: a vote for me is a vote for ____.",
    "White people like ____.",
    "Whoooo! Damn I love ____!",
    "Why am I broke?",
    "Why am I so tired?",
    "Why am I sticky?",
    "Why can't I sleep at night?",
    "Why did the chicken cross the road?",
    "Why do I hurt all over?",
    "With a one-time gift of just $10, you can save this child from ____.",
    "Would you like to try my signature cocktail, '____ on the Beach'?",
    "You are not alone. Millions of Americans struggle with ____ every day.",
    "You can't wait forever. It's time to talk to your doctor about ____.",
    "You guys, you can buy ____ on the dark web.",
    "You have violated the Prime Directive! You exposed an alien culture to ____ before they were ready.",
    "You know what's like, really funny when you think about it? ____.",
    "You know who else liked ____? Hitler.",
    "You say tomato, I say ____.",
    "You think you have defeated me? Well, let's see how you handle ____!",
    "You Won't Believe These 15 Hilarious ____ Bloopers!",
    "You won't believe what's in my pocket. It's ____.",
    "Your father was a powerful wizard, Harry. Before he died, he left you something very precious: ____.",
    "Your persistence is admirable, my dear Prince. But you cannot win my heart with ____ alone.",
    "You're not going to believe this, but I'm you from the future! You've got to stop ____.",
    "You've seen the bearded lady! You've seen the ring of fire! Now, ladies and gentlemen, feast your eyes upon ____!"
    ]

}
